FORMAT: 1A

# SwoleMate
Swolemate 

# Group Swolemate
Swolemate-related resources of the **Swolemate API**

## Login and Account [/login]
### Login and begin session [POST]
+ Request (application/json)

        {
            "username" : "ExampleUserName",
            "password" : "ExamplePassword"
        }

+ Response 200 (application/json)

        {
          "session-token" : "dfspoaidjf098j43i"
        }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
