FORMAT: 1A

# SwoleMate
The overview of the Swolemate API 

# Group Swolemate
Swolemate-related resources of the **Swolemate API**

## Login and Account [/login]
### Login and begin session [POST]
+ Request (application/json)

        {
            "username" : "ExampleUserName",
            "password" : "ExamplePassword"
        }

+ Response 200 (application/json)

        {
          "session-token" : "dfspoaidjf098j43i"
        }

## Dashboard [/dashboard/{username}]
### Get a user's dashboard, which returns the user's info and its swolationship [GET]
+ Parameters
    + username (required, alphanumeric, `foobarjones1` ) ... `username` whose dashboard you are fetching.

+ Request (application/json)
        
        {
            "session-token" : "asoifj9sa8jdioas"
        }
        
+ Response 200 (application/json)
        
        
            {
              "User": {
                "Info": {
                  "Name": "Scott Jacobson",
                  "Avatar": "this_user_icon.png"
                },
                "MatchingParams": {
                  "Type": "{Strength / Cardio / Both}",
                  "DistanceRequirement": "10 {Miles}",
                  "Location": "22.23232, 234.3432",
                  "Frequency": "{1-2, 3-5, 6-7} Days"
                },
                "Swolationship_Info": {
                  "Other_User_ID": "OtherUser55",
                  "Swolationship_ID": "asd0f87ouiahero9"
                }
              },
              "Swolationship": {
                "Swolationship_ID": "asd98fpjioasdf",
                "User_1_ID": "ScottJacobson1",
                "User_2_ID": "OtherUser55",
                "Goals": [
                  {
                    "ID": "dsaf9a8pudofiajls",
                    "Name": "Example Goal Name",
                    "User_1_Complete": true,
                    "User_2_Complete": false
                  }
                ]
              }
            }
        

## Swolationship [/swolationship/{s_id}]
A single Swolationship object with all its details including an array of Goals and an array of Messages

+ Parameters
    + s_id (required, alphanumeric, `34289f6c8eb5436fbb3a33ece845c61a`) ... MD5 hash `id` of the swolationship to perform action with. Has example value.

### Retrieve a Swolationship [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Swolationship [DELETE] 
+ Response 204

### Goal [/swolationship/{s_id}/goal/{g_index}]
A single goal object, which is a member of the `goals` array in a swolationship

+ Model

    + Header
        
            Parent : s_id
            Final-Index : g_index
    + Body
    
            {
              "ID": "dsaf9a8pudofiajls",
              "Name": "Example Goal Name",
              "Body": "Example goal body. This is a description you can type in",
              "User": {
                "UserName01": {
                  "complete": false
                },
                "TheOtherUserName": {
                  "complete": true
                }
              }
            }

+ Parameters
    + s_id (required, alphanumeric, `34289f6c8eb5436fbb3a33ece845c61a`) ... MD5 hash `id` of the swolationship to perform action with. Has example value.
    + g_index (optional, numeric, `4`) ... numeric `index` of the swolationship's goals array to perform action with if action is not PUT. Has example value.


####Get a Goal [GET]
+ Response 200 (application/json)
        
    [Goal][]

####Create a Goal [PUT]
+ Request (application/json)


+ Response 201 (application/json)

    [Goal][]

#### Goal Completion [/swolationship/{s_id}/goal/{g_index}/{username}]
Goal completion is signified by a POST in the `user_name` endpoint of a particular
goal. A DELETE in the same endpoint will remove the completion. All requests
return the updated Goal object.

+ Parameters
    + s_id (required, alphanumeric, `34289f6c8eb5436fbb3a33ece845c61a`) ... MD5 hash `id` of the swolationship to perform action with.
    + g_index (required, numeric, `4`) ... numeric `index` of the swolationship's goals array to perform action with if action is not PUT.
    + username (required, alphanumeric, `foobarjones1` ) ... `username` whose goal completion you are modifying. Must be a participating user in the goal.

#####Post a Goal Completion [POST]
+ Request (application/json)

+ Response 200 (application/json)

    [Goal][]
    

#####Remove a Goal Completion [DELETE]
+ Request (application/json)

+ Response 200 (application/json)

    [Goal][]




